name: Release
on:
  push:
    # branches:
    #   - main
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build package
        run: |
          sudo apt-get install gettext
          python -m pip install -U pip build
          python -m build

      - name: Upload source distribution as an action artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/bulma-sphinx-theme-*.tar.gz

      - name: Upload wheel distribution as an action artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/bulma-sphinx-theme-*-py3-none-any.whl

      - name: Make a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.4.1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.TESTPYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     verbose: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
